### ISSUE TITLE
Update for Angular 7+

### ISSUE THREAD

**Issue by vladkasianenko** [ultrasonicsoft/ng-connection-service#14]
When trying to update Angular Version from 7.2.15 to the 8 via `ng update`, it gives me an error:
`ackage "ng-connection-service" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").` and `Package "ng-connection-service" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").`
Can you please update peer dependency?

**Comment by rubenheymans** [comment]
it works for me on angular 8

**Comment by danielsteiner** [comment]
@rubenheymans good for you, though this has nothing to do with this issue.  Projects using this can't be updated to Angular 8 (or newer) since the dependencies are outdated.

**Comment by rubenheymans** [comment]
@danielsteiner you can update the packacke by setting the latests version number in package.json, and maybe add a flag to npm i to ignore the dependencies, don't remember which one though

**Comment by ultrasonicsoft** [comment]
@vladkasianenko @rubenheymans @danielsteiner 
Package has been updated and released on NPM. Please refer to the latest version supporting Angular v9-v15.
