### ISSUE TITLE
Cannot use `ConnectionServiceOptions` in latest version

### ISSUE THREAD

**Issue by hughjdavey** [ultrasonicsoft/ng-connection-service#15]
The [README](https://github.com/ultrasonicsoft/ng-connection-service/blob/master/README.md) and other files were updated 12 days ago, but the latest release on npm is `1.0.4` which is 10 months old. This version does not allow configuration of the `ConnectionServiceOptions` object that the README describes.

Thanks for your time

**Comment by KISINGA** [comment]
Facing same thing

**Comment by carlos-lopez-i3net** [comment]
Same here. Got any solution?

**Comment by Rehan1579** [comment]
https://github.com/ultrasonicsoft/ng-connection-service/issues/23#issuecomment-599224104

**Comment by TanayBhalani** [comment]
Use [ngx-connection-service](https://www.npmjs.com/package/ngx-connection-service)
It is forked from latest version of this project, and the npm package is also the latest of this project

**Comment by ultrasonicsoft** [comment]
@hughjdavey @kisinga @carlos-lopez-i3net 

Package has been updated and released on NPM. Please refer to the latest version supporting Angular v9-v15.
