### ISSUE TITLE
Upgrade for Angular 8

### ISSUE THREAD

**Issue by mohamedaboelmagd** [ultrasonicsoft/ng-connection-service#16]
Package "ng-connection-service" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").

**Comment by MauricioFerraz** [comment]
quoting my own message on a pull request to this project

> You can get away with copying the connection-service.service at [/projects/connection-service/src/lib/connection-service.service.ts@`master`](https://github.com/ultrasonicsoft/ng-connection-service/blob/master/projects/connection-service/src/lib/connection-service.service.ts) [](/ultrasonicsoft/ng-connection-service/blob/HEAD@{2019-06-27T17:43:34Z}/projects/connection-service/src/lib/connection-service.service.ts) and just adding it to your project, taking care to add the npm packages that it requires to your package.json, like lodash.

**Comment by Maximaximum** [comment]
Upgrading to support Angular 8 would be very extremely useful

**Comment by jotae1e** [comment]
I make a pull request.  You can use it for the time being:

`npm install jotae1e/ng-connection-service#master`

**Comment by pedrotcm** [comment]
Waiting for support Angular 8.

**Comment by boodahDEV** [comment]
It does not work well in angular 8

**Comment by instantaphex** [comment]
@boodahDEV  What issues specifically are you experiencing with Angular 8?  I'm doing the upgrade right now and trying to decide if I should go with another package or fork this one.

**Comment by eduardodallmann** [comment]
I'm using on Angular 8 and it works normally

**Comment by dafneolca** [comment]
is there an update on this issue?

**Comment by ArvinthC-GoSharp** [comment]
Can't update my Angular to version 9 and upper, since ng-connection-service showing an error, 
 'Package "ng-connection-service" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "9.0.0")

**Comment by ultrasonicsoft** [comment]
@pedrotcm @Maximaximum @instantaphex @MauricioFerraz @mohamedaboelmagd @ArvinthC-GoSharp @boodahDEV @eduardodallmann

Package has been updated and released on NPM. Please refer to the latest version supporting Angular v9-v15.
