### ISSUE TITLE
currentState is a boolean

### ISSUE THREAD

**Issue by KoIIIeY** [ultrasonicsoft/ng-connection-service#18]
Your example is wrong or outdated as I can see.

currentState is a boolean so 

this.hasNetworkConnection = currentState.hasNetworkConnection;
      this.hasInternetAccess = currentState.hasInternetAccess;

doesn't work

**Comment by Fcakiroglu16** [comment]
definitely

**Comment by ksdinesh27** [comment]
Looks like the npm package is still the old version 1.0.4

**Comment by Rehan1579** [comment]
https://github.com/ultrasonicsoft/ng-connection-service/issues/23#issuecomment-599224104

**Comment by TanayBhalani** [comment]
Use [ngx-connection-service](https://www.npmjs.com/package/ngx-connection-service)
It is forked from latest version of this project, and the npm package is also the latest of this project

**Comment by ultrasonicsoft** [comment]
@KoIIIeY I will update the documentation and package.

**Comment by ultrasonicsoft** [comment]
@KoIIIeY @Fcakiroglu16 
Package has been updated and released on NPM. Please refer to the latest version supporting Angular v9-v15.
