### ISSUE TITLE
npm installs version 1.0.4 even with ng-connection-service@latest

### ISSUE THREAD

**Issue by Beniyoo** [ultrasonicsoft/ng-connection-service#19]
Check and correct this please, thank you

**Comment by G00golplexian** [comment]
same here

**Comment by lewisvail3** [comment]
Looking at NPM registry, it looks like there hasn't been a version of this library published in over a year, despite the fact that there have been changes to the repo.

**Comment by Rehan1579** [comment]
https://github.com/ultrasonicsoft/ng-connection-service/issues/23#issuecomment-599224104

**Comment by TanayBhalani** [comment]
Use [ngx-connection-service](https://www.npmjs.com/package/ngx-connection-service)
It is forked from latest version of this project, and the npm package is also the latest of this project

**Comment by ultrasonicsoft** [comment]
@Beniyoo @G00golplexian @lewisvail3 
Package has been updated and released on NPM. Please refer to the latest version supporting Angular v9-v15.
