### ISSUE TITLE
it don't work in angular 8

### ISSUE THREAD

**Issue by Fcakiroglu16** [ultrasonicsoft/ng-connection-service#23]

**Comment by MaximeCallebaut** [comment]
Has anyone found a solution for this?

**Comment by Rehan1579** [comment]
> 
> 
> Has anyone found a solution for this?

yes, i just did, following are the steps i followed.

1- first of all, run following command in your project and it will install the old version from npm

> npm install ng-connection-service --save

2- download latest code/project from git 
3- open that project and run npm-install
4- a dist folder will be generated (containing the latest version)
5- replace ng-connection-service  with dist in your project's node-modules
6- now copy version# (3.0.0 right now) from dist and replace it in your project's package.json

Hope, it helps

**Comment by geno-github** [comment]
This seems to be a workaround for DEV but how would one get this workaround to work in Prod when a build is created from the package.json file?

**Comment by TanayBhalani** [comment]
Use [ngx-connection-service](https://www.npmjs.com/package/ngx-connection-service)
It is forked from latest version of this project, and the npm package is also the latest of this project

**Comment by ultrasonicsoft** [comment]
Updated package for v9-v15 support. Refer https://github.com/ultrasonicsoft/ng-connection-service/issues/30
