### ISSUE TITLE
Create a release that supports Angular v8

### ISSUE THREAD

**Issue by Maximaximum** [ultrasonicsoft/ng-connection-service#30]
Even though the master branch already seems to support Angular v8, there's no relevant npm release that we could use with Angular v8

**Comment by Rehan1579** [comment]
https://github.com/ultrasonicsoft/ng-connection-service/issues/23#issuecomment-599224104

**Comment by Maximaximum** [comment]
It seems like now we need a release that would support Angular v9 already :)

**Comment by AurelianGaiu** [comment]
@Maximaximum now there is also a need for Angular v10

**Comment by ultrasonicsoft** [comment]
Hi @Maximaximum, I have published new version supporting v9 till v15. Can you upgrade your v8 to v9 or something higher? I will try to publish a proper v8 supported release soon.
