### ISSUE TITLE
How to revitalize this project?

### ISSUE THREAD

**Issue by Maximaximum** [ultrasonicsoft/ng-connection-service#32]
Seems like this project is dead :( 

There have been no updates for 2 years. The latest ng-connection-service release only supports Angular v 6. As of today, we have Angular 9.

@ultrasonicsoft Could you please give a hint if there's any way to bring this project back to life? If you don't have time for this, maybe you could share ownership or allow someone else to commit to the master branch and make npm releases?

It would be really cool if the community could continue enjoying using this package

**Comment by ultrasonicsoft** [comment]
@Maximaximum I have been caught up with many other things and I couldn't maintain this project. Nevertheless, now I will go through issues and upgrade the version.
