### ISSUE TITLE
Piles of console error when http fails

### ISSUE THREAD

**Issue by TanayBhalani** [ultrasonicsoft/ng-connection-service#39]
The console.error can be replaced to [throwError ](https://rxjs-dev.firebaseapp.com/api/index/function/throwError) of rxjs or throw of javascript to prevent the piles of error in console when i do not want.
I faced issue of http error when network was down, and the console was constantly filled with errors, which i have no control on

if the methods throws error i can create a try catch block while subscribing the observable and decide what i want to do of error

https://github.com/ultrasonicsoft/ng-connection-service/blob/317eedca32de2c402145da2ced76397932cb803b/projects/connection-service/src/lib/connection-service.service.ts#L119-L123

**Comment by TanayBhalani** [comment]
You can check my example to understand the scenario
**Repro steps**
1. Click on Start Monitoring button
![image](https://user-images.githubusercontent.com/52976723/89382105-d8382800-d717-11ea-9ecd-2a1473581472.png)
2. Open console
![image](https://user-images.githubusercontent.com/52976723/89382247-2b11df80-d718-11ea-9419-cd5676e74c7f.png)
3. Disconnect your device from internet
4. Observe the console
![image](https://user-images.githubusercontent.com/52976723/89382485-9065d080-d718-11ea-801a-20a80abc9c8b.png)

Note: I have kept try catch block around _**subscribeMonitor()**_ Method in **_service check-connection.service.ts_** but its not able to catch because of console.error() implemented inside the method

[https://angular-ivy-jzg6ya.stackblitz.io](https://angular-ivy-jzg6ya.stackblitz.io)

**Comment by ultrasonicsoft** [comment]
okay, I will look into it

**Comment by ultrasonicsoft** [comment]
Hi @TanayBhalani, please check new version upgrade 9.0.3. Now throwing error when heartBeatUrl is not reachable. You can catch it and handle per your business logic.
