### ISSUE TITLE
Does not work on windows 10

### ISSUE THREAD

**Issue by hilkojj** [ultrasonicsoft/ng-connection-service#4]
I tried using this in my project and it works on Android (chrome).
However on Windows 10 (chrome & firefox) it will always say it is online. Both in the 'working-demo' and in my own project.

Update:
I noticed that `navigator.onLine` also says `true` when I'm not online.

**Comment by ultrasonicsoft** [comment]
I have built it with Windows 10 and Chrome. Need to test with Firefox.

**Comment by oxydeon** [comment]
same problem for me on Chrome Windows 10

**Comment by ultrasonicsoft** [comment]
Please create an example GitHub repository to reproduce this issue.

**Comment by oxydeon** [comment]
I have also the problem with the demo site

airplane mode and `navigator.onLine` also says `true`

![image](https://user-images.githubusercontent.com/8861081/51682616-1ebbab00-1fe8-11e9-820b-0c3c434b1acb.png)

**Comment by ultrasonicsoft** [comment]
That's weird. I couldn't reproduce it. Can you share Google Chrome version please?

**Comment by ultrasonicsoft** [comment]
That's weird. I couldn't reproduce it. Can you share Google Chrome version please?

**Comment by oxydeon** [comment]
Last version of Windows, last version of Chrome: 71.0.3578.98 (Build officiel) (64 bits)

I try to disable all my extension to be sure, same problem...

**Comment by ssc-mmartell** [comment]
I'm experiencing the same problem. Windows 10, Chrome Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by ultrasonicsoft** [comment]
#11
