### ISSUE TITLE
Please update to angular v10 (v11 since 2020-11-11)

### ISSUE THREAD

**Issue by BruneXX** [ultrasonicsoft/ng-connection-service#44]
Hi guys is there a chance that you can update this to angular v10 ?

**Comment by javierarocena** [comment]
Same here... 😞

**Comment by sedrak1987** [comment]
pls update for angular 11

**Comment by BruneXX** [comment]
Hi Guys any update on this? how can I assist on this? Please just let me know :)

**Comment by bkrajendra** [comment]
I tried following in ng 11:

1) git clone https://github.com/ultrasonicsoft/ng-connection-service.git
2) cd ng-connection-service
3) npm i --save-dev @angular-devkit/build-angular
4) npm i --save-dev @angular-devkit/build-ng-packagr
5) npm run build_lib

This will generate ```ng-connection-service``` in dist folder.
you can copy this folder in node-module folder and try using this service as mentioned in read me.
you can also try installing the local folder with npm install ../ng-connection-service

Note: don't forget to copy ping.json to your asset folder

It worked for me in Angular 11

**Comment by BruneXX** [comment]
Hi @bkrajendra thanks, but I don’t want to do that, I just want this component updated, I think that I’ll fork and add support for ng11 by myself.  Because I’ve reported this some time ago and I don’t know if this repo is still mantained..

**Comment by javierarocena** [comment]
An updated ng11 suported fork could be awesome

**Comment by BruneXX** [comment]
Ok, I'll make a fork and update this as soon as I can, I'll share the link here when it's done.

**Comment by BruneXX** [comment]
I've not tested it yet, but here it is: https://www.npmjs.com/package/ngxc-connection-service should support ng11 now.

**Comment by javierarocena** [comment]
Hi @BruneXX , I tested your fork and get this error:

```
ERROR Error: Uncaught (in promise): Error: This constructor was not compatible with Dependency Injection.
Error: This constructor was not compatible with Dependency Injection.
```

I just replaced:
`import { ConnectionService } from 'ng-connection-service';
`

With
`import { ConnectionService } from 'ngxc-connection-service';
`

Any ideas? Thanks!

**Comment by BruneXX** [comment]
Hi @javierarocena I'll take a look as soon as I can, I was a bit busy these days and I had no time to test it, I'll took a look soon, thanks for your comment :)

**Comment by ElCarsten** [comment]
@javierarocena You need to update the package by this command `npm install ngxc-connection-service --save` first

**Comment by kingBradely** [comment]
Hi, I just installed this library to know the status of my connection status, but when I make the import to my online service it tells me
Could not find a declaration file for module 'ngxc-connection-service'
