### ISSUE TITLE
Please provide an  upgrade for Angular 9+ 

### ISSUE THREAD

**Issue by saeidehmsm** [ultrasonicsoft/ng-connection-service#45]
Please provide an  upgrade for Angular 9+ . Thanks.

**Comment by Alireza-ce** [comment]
> 
> 
> Please provide an upgrade for Angular 9+ . Thanks.

it's working on angular 9+.for watching changes turn on offline mode in the dev console

**Comment by ultrasonicsoft** [comment]
upgraded to angular 11
