### ISSUE TITLE
Need support for mobile(cordova) app. 

### ISSUE THREAD

**Issue by saeidehmsm** [ultrasonicsoft/ng-connection-service#46]
I have a mobile version of my angular app. I'm using this plugin. However doesn't work for cordova. please provide a support for mobile app. 
Thanks.

**Comment by yigsvnsla** [comment]
if your proyect its running in cordova, try use capacitor js and your complement network extension

**Comment by ultrasonicsoft** [comment]
@saeidehmsm  you can check this plugin.
https://cordova.apache.org/docs/en/10.x/reference/cordova-plugin-network-information/
