### ISSUE TITLE
App not detecting the first state

### ISSUE THREAD

**Issue by guisperandio** [ultrasonicsoft/ng-connection-service#7]
When you build the production project and start that using a service work when you turn the internet off and reload the page, the service doesn't detect that you are offline, and i cant initialize the variable.

**Comment by ultrasonicsoft** [comment]
#11

**Comment by jorgeandresserrano** [comment]
Probably implementing the solution in the package would be better than walkarounds? Cheers!

**Comment by jorgeandresserrano** [comment]
The variable can be initialized using `this.isConnected = navigator.onLine;`
