### ISSUE TITLE
Not working on Chrome and Firefox

### ISSUE THREAD

**Issue by itsgreat2beme** [ultrasonicsoft/ng-connection-service#8]
Not working on Chrome Version 72.0.3626.81 (Official Build) (64-bit). Also not on firefox.

**Comment by kheronn** [comment]
Hi.

Here not worked in version 71.0.3578.98.

**Comment by mtemel123** [comment]
u can use
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events
not need this lib.

**Comment by ultrasonicsoft** [comment]
@mtemel123 this library is using mentioned events. Could you please confirm that these events work on mentioned browser version and this library does not?

**Comment by mtemel123** [comment]
> @mtemel123 this library is using mentioned events. Could you please confirm that these events work on mentioned browser version and this library does not?

https://caniuse.com/#search=navigator.onLine

**Comment by ultrasonicsoft** [comment]
okay.
